### PR TITLE
Ensure all nodes are up & discovered in upgrade bwc tests

### PR DESCRIPTION
**Pull request by mfussenegger**
Also increase cratedb heap size to 1GB, see commits.

### CODE REVIEW

**Comment by matriv** [comment]
retest this please

**Comment by matriv** [comment]
Seems that increasing the heap size in combination with asserting all nodes are discovered helps with the timeouts.

**Review by BaurzhanSakhariev — APPROVED** [review]

**Comment by matriv** [comment]
retest this please

**Comment by matriv** [comment]
hm, it failed again, so maybe we should wait for @mfussenegger to continue his investigation.

**Pull request merged**
