### PR TITLE
Add CrateDB 5.6.0 to BWC tests

### PR DESCRIPTION
**Pull request by seut**

### CODE REVIEW

**Comment by seut** [comment]
retest this please

**Comment by matriv** [comment]
retest this please

**Review by mfussenegger — APPROVED** [review]
lgtm, but let's wait for 5.6.1 before merging due to the 5.6.0 JDK issue.

**Comment by BaurzhanSakhariev** [comment]
I think we can we merge this now? 
On master we have 5.5 -> nightly which is essentially testing 5.5 -> 5.7

**Comment by matriv** [comment]
> I think we can we merge this now? On master we have 5.5 -> nightly which is essentially testing 5.5 -> 5.7
> 
> But maybe after #306 otherwise it won't pass CI tests

Thx for the reminder here @BaurzhanSakhariev.
I'll wait for https://github.com/crate/crate-qa/pull/306 to be merged first, and then I'll merge it.

**Pull request merged**
