### PR TITLE
Add allocation filtering recovery test

### PR DESCRIPTION
**Pull request by mkleen**
## Summary of the changes / Why this is an improvement

This test ensures that replicas are auto-expanding according to the allocation filtering rules. Since versions < 4.4 of nodes do not have the related bp (https://github.com/crate/crate/pull/10734 ) implemented, these nodes would not be filtered at all. Therefore this can only be tested from 4.4 forwards. For this reason the test is not an exact port from the original version from https://github.com/elastic/elasticsearch/blob/master/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/RecoveryIT.java but instead focuses on covering the filter application while going through an upgrade of a cluster. 

Once 4.4 is released this would serve as a starting point to upgrade to the newer versions.

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by mkleen** [comment]
retest this please

**Comment by mkleen** [comment]
retest this please

**Comment by mkleen** [comment]
retest this please

**Comment by mkleen** [comment]
retest this please

File "/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/env/lib/python3.7/site-packages/crate/client/http.py", line 583, in _drop_server

    "exception from last server: %s") % message)

crate.client.exceptions.ConnectionError: No more Servers available, exception from last server: HTTPConnectionPool(host='127.0.0.1', port=4200): Read timed out. (read timeout=1)

**Comment by mkleen** [comment]
retest this please

**Review by mfussenegger — APPROVED** [review]

**Pull request merged**
