### PR TITLE
node-postgres: Improve test suite

### PR DESCRIPTION
**Pull request by amotl**
Hi there,

this builds upon #180 and adds some more improvements.

- Run all test cases on both "pure-JS" and "native" variants of `node-postgres`.
    `node-postgres` offers two different driver variants, a _pure-JavaScript_ driver variant and a _native_ driver variant. This improvement will spawn a matrix to run all defined test cases on both variants.
- Refactor the layout of the custom test suite a bit more, so we now have a `libs` vs. a `tests` folder.
- Fix the Jenkins/Docker infrastructure setup to satisfy the upgrade of `node-gyp`, which apparently is required for a sound installation of `libpq`/`pg-native`. Sigh.
- Instead of `expect`, use Chai's `assert` assertion style.
- Improve README
    Add some documentation about how to
    a) run different variants of CrateDB through Docker and
    b) run test suite on a different version of Node.js through `nodeenv`

With kind regards,
Andreas.

P.S.: Sorry for the anomaly on the test environment setup introduced by f1a769c. However, @seut and me already spent hours on that. Please follow the inline links to learn more about the background of the respective mitigations, more details are at https://github.com/crate/crate-qa/pull/185#issuecomment-772956587. Let's finally migrate to GitHub Actions where things just work (TM) ;] and is battle-tested by so many people using it.

### CODE REVIEW

**Comment by amotl** [comment]
Hi.

The error observed at [1] somehow indicates that the job might not be running within a Docker container at all.

Can you help to investigate this if you can afford a minute, @seut? At least having a look and confirming or rejecting my observation will help already. Afterwards, I might continue digging deeper. Thanks already!

<details>
<summary>libpq traceback</summary>

```
/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/bindings/bindings.js:126
  err = new Error(
        ^

Error: Could not locate the bindings file. Tried:
 → /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/build/addon.node
 → /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/build/Debug/addon.node
 → /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/build/Release/addon.node
 → /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/out/Debug/addon.node
 → /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/Debug/addon.node
 → /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/out/Release/addon.node
 → /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/Release/addon.node
 → /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/build/default/addon.node
 → /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/compiled/15.6.0/linux/x64/addon.node
 → /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/addon-build/release/install-root/addon.node
 → /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/addon-build/debug/install-root/addon.node
 → /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/addon-build/default/install-root/addon.node
 → /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/lib/binding/node-v88-linux-x64/addon.node
    at bindings (/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/index.js:1:46)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/pg-native/index.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1108:14) {
  tries: [
    '/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/build/addon.node',
    '/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/build/Debug/addon.node',
    '/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/build/Release/addon.node',
    '/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/out/Debug/addon.node',
    '/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/Debug/addon.node',
    '/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/out/Release/addon.node',
    '/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/Release/addon.node',
    '/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/build/default/addon.node',
    '/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/compiled/15.6.0/linux/x64/addon.node',
    '/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/addon-build/release/install-root/addon.node',
    '/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/addon-build/debug/install-root/addon.node',
    '/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/addon-build/default/install-root/addon.node',
    '/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq/lib/binding/node-v88-linux-x64/addon.node'
  ]
}
```
</details>

With kind regards,
Andreas.

[1] https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa_on_pr/detail/crate_qa_on_pr/516/pipeline#step-219-log-99

**Comment by seut** [comment]
@amotl 

Isn't it just a missing `libpq-dev` install cmd at https://github.com/crate/crate-qa/blob/master/tests/client_tests/node-postgres/Dockerfile#L6 ?

**Comment by amotl** [comment]
I checked that already:
```sh
docker run -it --rm --volume $(pwd):/develop node:15-buster bash

root@11933b31cc80:/# apt install libpq5 libpq-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libpq-dev is already the newest version (11.9-0+deb10u1).
libpq5 is already the newest version (11.9-0+deb10u1).
libpq5 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

after also running
```sh
cd /develop
npm install --verbose
```

this command is successful and doesn't croak:
```sh
node --eval="require('pg').native"
```

**Comment by amotl** [comment]
I've just added 8d19e01 and [1] says:
```
Hostname: c0618a3448d8
Node.js version: v15.6.0
```

So, the job apparently **is** running within a Docker container. I just got confused by the path naming to say `/var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/env`.

However, so something other fishy thing must be going on there.

[1] https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa_on_pr/detail/crate_qa_on_pr/517/pipeline#step-219-log-1

**Comment by amotl** [comment]
> `libpq-dev` is apparently already included in `node:15-buster`.

Nevertheless, I just added 512239d.

**Comment by amotl** [comment]
Still no joy [1].

[1] https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa_on_pr/detail/crate_qa_on_pr/518/pipeline/39#step-273-log-105

**Comment by amotl** [comment]
After increasing verbosity by saying `npm install --verbose`, it reveals [1]:
```
npm ERR! gyp: Call to '/usr/bin/pg_config --libdir' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:329:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
npm ERR! gyp ERR! System Linux 4.18.5-1.el7.elrepo.x86_64
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq
npm ERR! gyp ERR! node -v v15.2.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm verb exit 1
```

[1] https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa_on_pr/detail/crate_qa_on_pr/519/pipeline/39#step-273-log-778

---

On a side note, this job said [2] to run on
```
Hostname: 08e8d7473480
Node.js version: v15.2.1
```

On the other hand, when invoking `node:15-buster` on my workstation, it says
```
$ docker run -it --rm node:15-buster bash
root@c1061f7dc2f6:/# node --version
v15.7.0
```

[2] https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa_on_pr/detail/crate_qa_on_pr/519/pipeline/39#step-273-log-1

**Comment by amotl** [comment]
### Further investigations wrt. test isolation with Jenkins/Docker

The job where the reported Node.js version was...

- ... `v15.6.0` ran on `jenkins-04.bregenz.a1.cr8.net`, see https://github.com/crate/crate-qa/pull/185#issuecomment-772565470 and [1].
- ... `v15.2.1` ran on `jenkins-05.bregenz.a1.cr8.net`, see https://github.com/crate/crate-qa/pull/185#issuecomment-772593620 and [2].

[1] https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa_on_pr/detail/crate_qa_on_pr/517/pipeline/#step-218-log-2
[2] https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa_on_pr/detail/crate_qa_on_pr/519/pipeline/39/#step-272-log-2

**Comment by amotl** [comment]
Halleluja.

```
SUCCESS [native: false]: test_parameterized_timestamp
SUCCESS [native: false]: test_insert_multivalue
SUCCESS [native: true]: test_insert_multivalue
SUCCESS [native: true]: test_parameterized_timestamp
Overall success: true
```

-- https://jenkins.crate.io/blue/organizations/jenkins/CrateDB%2Fqa%2Fcrate_qa_on_pr/detail/crate_qa_on_pr/540/pipeline/30#step-247-log-355

**Comment by amotl** [comment]
>  I will try to improve the patch by moving parts of the recipe back into the Dockerfile in order to trim down the Jenkins recipe again.

No joy. I tried a5dae1d but this is tripping the build again. So, I will retract this commit again and leave it like it has been successful before.
```
npm ERR! gyp: Call to '/usr/bin/pg_config --libdir' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 4.18.5-1.el7.elrepo.x86_64
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres/node_modules/libpq
npm ERR! gyp ERR! node -v v15.8.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm verb exit 1
```

**Comment by amotl** [comment]
Hi again,

I tried to run it on `node:14-buster` with ea89265 but it croaks with yet another permission error.
```
+ pip3 install --upgrade cr8
The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Looking in indexes: https://pypi.org/simple, https://pypi.cr8.net/
Collecting cr8
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/root/.cache/pip/wheels/e8/48/1a/de35f28d60bfb5c9ceb12a1160bce54503d4050ffaf42a3802'
Check the permissions.
script returned exit code 1
```

So, we will at least need some of the permission problem mitigations again.

With kind regards,
Andreas.

cc @seut

**Comment by amotl** [comment]
> run it on `node:14-buster` with reverting all the other countermeasures

Same thing. No joy.
```
npm verb stack Error: libpq@1.8.9 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1048:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm verb pkgid libpq@1.8.9
npm verb cwd /var/lib/jenkins/workspace/CrateDB/qa/crate_qa_on_pr/tests/client_tests/node-postgres
npm verb Linux 4.18.8-1.el7.elrepo.x86_64
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm verb node v14.15.4
npm verb npm  v6.14.10
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libpq@1.8.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Review by seut — APPROVED** [review]
👍 thanks for hunting it down!

btw. maybe squash commits so that only successful once stay

**Comment by amotl** [comment]
JFYI.

> A fork [and apparently, a rewrite] of the GYP build system for use in the Node.js projects.

https://github.com/nodejs/gyp-next

**Pull request merged**
