### PR TITLE
Add 5.5.x to bwc tests

### PR DESCRIPTION
**Pull request by matriv**

### CODE REVIEW

**Review by seut — APPROVED** [review]
👍 thx

**Review by BaurzhanSakhariev — APPROVED** [review]

**Comment by matriv** [comment]
We probably need one nightly build with master now on 5.6.0 to pass the tests, will wait until tomorrow.

**Comment by matriv** [comment]
retest this please

**Comment by matriv** [comment]
retest this please

**Comment by seut** [comment]
retest this please

**Pull request merged**
