### PR TITLE
Ensure users persist across version upgrades

### PR DESCRIPTION
**Pull request by mfussenegger**
Also makes the default test output a bit more verbose - showing the upgrade path permutations:

```
Start version: 4.1.x
    Upgrade to: 4.2.x
    Upgrade to: 4.3.x
    Upgrade to: 4.4.x
    Upgrade to: 4.5.x
    Upgrade to: 4.6.x
    Upgrade to: 4.7.x
    Upgrade to: 4.8.x
    Upgrade to: 5.0.x
    Upgrade to: 5.1.x
    Upgrade to: 5.2.x
    Upgrade to: 5.3.x
    Upgrade to: 5.4.x
    Upgrade to: 5.5.x
    Upgrade to: latest-nightly
Start version: 4.2.x
    Upgrade to: 4.3.x
    Upgrade to: 4.4.x
-
```

### CODE REVIEW

**Comment by mfussenegger** [comment]
I could also add rolling upgrade tests, but not sure if there's much point if we don't support it for mixed 5.5, 5.6 clusters. I guess that was your point yesterday @seut ?

**Comment by seut** [comment]
> I could also add rolling upgrade tests, but not sure if there's much point if we don't support it for mixed 5.5, 5.6 clusters. I guess that was your point yesterday @seut ?

Yes doesn't make sense to me. What we want to check on rolling upgrades to 5.6 is that any user/role/privilege statements are forbidden during the upgrade (mixed cluster).

**Review by seut — APPROVED** [review]
👍

**Comment by mfussenegger** [comment]
Merged because the test failure is related to a regression in crate with joins. the bwc test part passed

**Comment by matriv** [comment]
Thx @mfussenegger sorry for late response, Could you also add an assertion for the sys.privileges?
(will be handy very soon, with the privileges metadata migration)

**Pull request merged**
